# Generated by Django 3.2.3 on 2021-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='translatable',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
