# Generated by Django 3.2.3 on 2021-06-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms_api', '0002_auto_20210614_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='described_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='simple_cms_api.thing'),
        ),
    ]
