# Generated by Django 3.2.3 on 2021-06-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms_api', '0004_auto_20210615_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='described_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_description', to='simple_cms_api.thing'),
        ),
    ]
