# Generated by Django 3.2.3 on 2021-06-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simple_cms_api', '0005_alter_tenant_described_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='simple_cms_api.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='simple_cms_api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
